import logging
from contextlib import asynccontextmanager
from pathlib import Path

import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Global variable to cache forecasts
forecast_data: dict = {}


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Lifespan context manager to handle startup and shutdown events.
    Replaces the deprecated @app.on_event("startup").
    """
    # --- STARTUP LOGIC ---
    global forecast_data
    logger.info("Starting up application and loading forecasts...")
    try:
        project_root = Path(__file__).resolve().parents[2]
        forecast_file = project_root / "data" / "predictions" / "latest_forecasts.csv"

        if forecast_file.exists():
            df = pd.read_csv(forecast_file)
            # Convert to dictionary for fast lookup {asset_name: data}
            forecast_data = df.set_index("asset_name").to_dict(orient="index")
            logger.info(f"Successfully loaded forecasts for: {list(forecast_data.keys())}")
        else:
            logger.warning("No forecast file found. Ensure the training pipeline has run.")
            forecast_data = {}

    except Exception as e:
        logger.error(f"Error loading forecasts during startup: {e}")
        forecast_data = {}

    yield  # Application runs here

    # --- SHUTDOWN LOGIC (Optional) ---
    logger.info("Shutting down application...")
    forecast_data.clear()


# Initialize FastAPI with lifespan
app = FastAPI(
    title="Crypto-Stock Forecast API",
    description="Serves daily price predictions generated by Hybrid LSTM-XGBoost pipeline.",
    version="1.0",
    lifespan=lifespan,  # Inject the lifespan manager here
)


class ForecastResponse(BaseModel):
    asset_name: str
    last_date: str
    current_price: float
    forecast_price: float
    predicted_change_pct: float


@app.get("/health")
def health_check():
    """
    Health check endpoint to verify API status.
    """
    return {"status": "healthy", "assets_available": len(forecast_data) if forecast_data else 0}


@app.get("/predict/{asset_name}", response_model=ForecastResponse)
def get_prediction(asset_name: str):
    """
    Get the latest forecast for a specific asset by name.
    """
    if not forecast_data:
        raise HTTPException(status_code=503, detail="Forecast data not available yet.")

    # Case-insensitive lookup support (optional improvement)
    # We stick to exact match for now based on CSV
    if asset_name not in forecast_data:
        raise HTTPException(status_code=404, detail=f"Asset '{asset_name}' not found.")

    data = forecast_data[asset_name]
    data["asset_name"] = asset_name  # Add name back to response
    return data


@app.get("/predict", response_model=list[ForecastResponse])
def get_all_predictions():
    """
    Get forecasts for all available assets.
    """
    if not forecast_data:
        return []

    results = []
    for name, data in forecast_data.items():
        res = data.copy()
        res["asset_name"] = name
        results.append(res)
    return results
