name: CD - Model Training Pipeline

on:
  workflow_dispatch:

jobs:
  train-and-log-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies into a new uv virtual environment
        run: |
          pip install uv
          uv venv
          uv pip install .

      - name: Create DVC credentials file from secret
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          mkdir -p .dvc/tmp
          cat << EOF > .dvc/tmp/gdrive-user-credentials.json
          ${GDRIVE_CREDENTIALS_DATA}
          EOF

      - name: Pull Data with DVC
        run: |
          uv pip install dvc[gdrive]
          uv run dvc pull -f

      - name: Run Model Training Script
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_EXPERIMENT_PATH: ${{ secrets.DATABRICKS_EXPERIMENT_PATH }}
        run: |
          uv run python src/models/train_model.py
